FROM jenkins/jenkins:lts

USER root

# Install Docker CLI (to run Cypress container) & Java
RUN apt-get update && \
    apt-get install -y docker.io openjdk-11-jdk && \
    apt-get clean

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

USER jenkins
